# Modules=a file containing code you want to include in your program 
#         use 'import' to include a module (built-in or your own)
#         useful to break up a large program reusable separate files  
# Ex=1
# import math
# print(math.pi)
# or
# import math as m
# print(m.pi)
# or
# from math import pi
# print(pi)

# Ex=2
# import math
# print(math.e)
# or
# import math as m
# print(m.e)
# or
# from math import e
# print(e)


# Ex=3
# import math
# a,b,c,d,e=1,2,3,4,5
# print(math.e ** a)
# print(math.e ** b)
# print(math.e ** c)
# print(math.e ** d)
# print(math.e ** e)

# import math as m
# a,b,c,d,e=1,2,3,4,5
# print(m.e ** a)
# print(m.e ** b)
# print(m.e ** c)
# print(m.e ** d)
# print(m.e ** e)

# from math import e
# a,b,c,d,e=1,2,3,4,5
# print(e ** a)
# print(e ** b)
# print(e ** c)
# print(e ** d)
# print(e ** e)

 





















